services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      NODE_ENV: production
      DB_NAME: bookingdb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      TOKENSECRET: ${TOKENSECRET}
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db